// Recruitment data
export const mockJobs = [
  {
    id: '1',
    title: 'Senior React Developer',
    department: 'Engineering',
    location: 'San Francisco, CA',
    salaryMin: 120000,
    salaryMax: 160000,
    skills: ['React', 'TypeScript', 'Node.js', 'AWS'],
    experienceRequired: 5,
    applicationDeadline: '2024-03-31',
    status: 'Active',
    applicants: 24,
    postedDate: '2024-02-01',
  },
  {
    id: '2',
    title: 'Product Manager',
    department: 'Product',
    location: 'New York, NY',
    salaryMin: 130000,
    salaryMax: 180000,
    skills: ['Product Strategy', 'Analytics', 'Leadership', 'Agile'],
    experienceRequired: 7,
    applicationDeadline: '2024-03-15',
    status: 'Active',
    applicants: 18,
    postedDate: '2024-02-05',
  },
  {
    id: '3',
    title: 'UX/UI Designer',
    department: 'Design',
    location: 'Remote',
    salaryMin: 90000,
    salaryMax: 130000,
    skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems'],
    experienceRequired: 3,
    applicationDeadline: '2024-04-01',
    status: 'Active',
    applicants: 32,
    postedDate: '2024-02-10',
  },
  {
    id: '4',
    title: 'Data Analyst',
    department: 'Analytics',
    location: 'Boston, MA',
    salaryMin: 85000,
    salaryMax: 120000,
    skills: ['SQL', 'Python', 'Tableau', 'Statistics'],
    experienceRequired: 2,
    applicationDeadline: '2024-03-20',
    status: 'Closed',
    applicants: 45,
    postedDate: '2024-01-15',
  },
];

export const mockCandidates = [
  {
    id: '1',
    name: 'John Smith',
    email: 'john.smith@email.com',
    phone: '+1-555-0101',
    location: 'San Francisco, CA',
    currentRole: 'Senior Developer',
    company: 'Tech Corp',
    experience: 6,
    skills: ['React', 'TypeScript', 'Node.js', 'AWS', 'Python'],
    education: 'B.S. Computer Science - Stanford University',
    rating: 5,
    status: 'Active',
    noticePeriod: '2 weeks',
    salaryExpectation: 150000,
    appliedJobs: ['1'],
  },
  {
    id: '2',
    name: 'Sarah Johnson',
    email: 'sarah.j@email.com',
    phone: '+1-555-0102',
    location: 'New York, NY',
    currentRole: 'Product Manager',
    company: 'Innovation Labs',
    experience: 8,
    skills: ['Product Strategy', 'Analytics', 'Leadership', 'Agile', 'User Research'],
    education: 'M.B.A. - Harvard Business School',
    rating: 4,
    status: 'Active',
    noticePeriod: '1 month',
    salaryExpectation: 170000,
    appliedJobs: ['2'],
  },
  {
    id: '3',
    name: 'Michael Chen',
    email: 'm.chen@email.com',
    phone: '+1-555-0103',
    location: 'Remote',
    currentRole: 'UX Designer',
    company: 'Creative Studios',
    experience: 4,
    skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'CSS'],
    education: 'B.A. Graphic Design - RISD',
    rating: 5,
    status: 'Active',
    noticePeriod: '3 weeks',
    salaryExpectation: 110000,
    appliedJobs: ['3'],
  },
  {
    id: '4',
    name: 'Emily Rodriguez',
    email: 'emily.r@email.com',
    phone: '+1-555-0104',
    location: 'Boston, MA',
    currentRole: 'Data Scientist',
    company: 'Analytics Plus',
    experience: 3,
    skills: ['Python', 'SQL', 'Tableau', 'Statistics', 'Machine Learning'],
    education: 'M.S. Data Science - MIT',
    rating: 4,
    status: 'Active',
    noticePeriod: '1 week',
    salaryExpectation: 115000,
    appliedJobs: ['4'],
  },
];

export const mockApplications = [
  {
    id: '1',
    candidateId: '1',
    jobId: '1',
    status: 'Shortlisted',
    appliedDate: '2024-02-15',
    notes: 'Strong technical background, excellent references',
    assignedRecruiter: 'Sarah Wilson',
    stage: 'Shortlisted',
  },
  {
    id: '2',
    candidateId: '2',
    jobId: '2',
    status: 'Interview Scheduled',
    appliedDate: '2024-02-18',
    notes: 'Perfect fit for PM role, MBA graduate',
    assignedRecruiter: 'Tom Harris',
    stage: 'Interview Scheduled',
  },
  {
    id: '3',
    candidateId: '3',
    jobId: '3',
    status: 'Applied',
    appliedDate: '2024-02-20',
    notes: 'Great portfolio, needs review',
    assignedRecruiter: 'Sarah Wilson',
    stage: 'Applied',
  },
  {
    id: '4',
    candidateId: '4',
    jobId: '4',
    status: 'Offer Extended',
    appliedDate: '2024-02-10',
    notes: 'Accepted offer, pending background check',
    assignedRecruiter: 'Tom Harris',
    stage: 'Offer Extended',
  },
];

export const mockInterviews = [
  {
    id: '1',
    applicationId: '1',
    candidateId: '1',
    candidateName: 'John Smith',
    type: 'Technical',
    scheduledDate: '2024-03-01',
    scheduledTime: '10:00 AM',
    mode: 'Online',
    interviewer: 'Alex Kumar',
    videoLink: 'https://meet.google.com/abc-defg-hij',
    status: 'Scheduled',
    rating: null,
    feedback: null,
  },
  {
    id: '2',
    applicationId: '2',
    candidateId: '2',
    candidateName: 'Sarah Johnson',
    type: 'Behavioral',
    scheduledDate: '2024-03-05',
    scheduledTime: '2:00 PM',
    mode: 'Office',
    interviewer: 'Jennifer Lee',
    videoLink: null,
    status: 'Completed',
    rating: 4.5,
    feedback: 'Excellent communication skills, strong leadership experience',
  },
];

export const mockFinance = {
  income: [
    {
      id: '1',
      amount: 50000,
      date: '2024-02-01',
      category: 'Consulting',
      paymentMethod: 'Bank Transfer',
      clientName: 'Enterprise Co',
      invoiceNumber: 'INV-001',
      status: 'Approved',
    },
    {
      id: '2',
      amount: 30000,
      date: '2024-02-15',
      category: 'Services',
      paymentMethod: 'Credit Card',
      clientName: 'StartUp Inc',
      invoiceNumber: 'INV-002',
      status: 'Pending',
    },
  ],
  expenses: [
    {
      id: '1',
      amount: 5000,
      date: '2024-02-05',
      category: 'Office Supplies',
      vendor: 'Office Max',
      status: 'Approved',
    },
    {
      id: '2',
      amount: 2500,
      date: '2024-02-10',
      category: 'Software',
      vendor: 'AWS',
      status: 'Pending',
    },
  ],
  payroll: [
    {
      id: '1',
      employeeId: 'E001',
      employeeName: 'John Doe',
      baseSalary: 6000,
      bonus: 1000,
      deductions: 800,
      netSalary: 6200,
      status: 'Paid',
      payDate: '2024-02-28',
    },
    {
      id: '2',
      employeeId: 'E002',
      employeeName: 'Jane Smith',
      baseSalary: 7000,
      bonus: 1500,
      deductions: 950,
      netSalary: 7550,
      status: 'Pending',
      payDate: '2024-02-28',
    },
  ],
};

export const mockPublicJobs = [
  { ...mockJobs[0], description: 'We are looking for an experienced React developer to join our team...' },
  { ...mockJobs[1], description: 'Lead product strategy and drive innovation in a fast-growing company...' },
  { ...mockJobs[2], description: 'Design beautiful and intuitive user experiences for millions of users...' },
];

export const emailTemplates = [
  {
    id: '1',
    name: 'Interview Invitation',
    subject: 'Interview Invitation - {{candidateName}}',
    body: 'Dear {{candidateName}},\n\nWe are pleased to invite you for an interview for the {{jobTitle}} position...',
  },
  {
    id: '2',
    name: 'Rejection Letter',
    subject: 'Application Status - {{jobTitle}}',
    body: 'Dear {{candidateName}},\n\nThank you for your interest in {{jobTitle}} position...',
  },
  {
    id: '3',
    name: 'Offer Letter',
    subject: 'Job Offer - {{jobTitle}}',
    body: 'Dear {{candidateName}},\n\nWe are delighted to extend an offer for the {{jobTitle}} position...',
  },
];
